#!/usr/bin/env bash

## Test site installation
##
## Usage: fin test


#-------------------------- Helper functions --------------------------------

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

# Debug mode switch
if [[ "${DEBUG}" != "" ]]; then
    set -x
fi

echo-yellow "Testing home page..."
RESULT=`curl -sL -I http://${VIRTUAL_HOST} | grep "HTTP/1.1 200 OK"`
if [[ $RESULT == "" ]]; then
  echo-red "No \"200 OK\" result from home page http://${VIRTUAL_HOST}"
else
  echo-green "Home page works! $RESULT"
fi
echo-yellow "Testing login page..."
RESULT=`curl -sL -I http://${VIRTUAL_HOST}/user/login | grep "HTTP/1.1 200 OK"`
if [[ $RESULT == "" ]]; then
  echo-red "No \"200 OK\" result from http://${VIRTUAL_HOST}/user/login"
else
  echo-green "Works! $RESULT"
fi
